### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [RobertElderSoftware/recc#3]
I would like to point out that identifiers like "[`__GENERATE_CODE__`](https://github.com/RobertElderSoftware/recc/blob/9389ef35121df604898f2f00c43a5bbd97a08afa/code_generator.h#L1)" and "[`__LEXER_H__`](https://github.com/RobertElderSoftware/recc/blob/9389ef35121df604898f2f00c43a5bbd97a08afa/lexer.h#L1)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by RobertElder** [comment]
Thanks for pointing that out, I had no idea they were reserved.

**Comment by RobertElder** [comment]
Fixed.

**Comment by elfring** [comment]
Would you also like to [reconsider consequences](https://github.com/RobertElderSoftware/recc/blob/586aa2d93acc9b990b5f876f613dc7b92ed3e0d4/recc-implementation/l0_generator.h#L1 "More update candidates") from [C++ naming conventions](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by RobertElder** [comment]
Yeah, if there are any identifiers that violate well-regarded standards than I would probably work toward eventually fixing them.  I looked at the SO post you linked, although I'm not sure which rule is being violated?

**Comment by elfring** [comment]
How do you think about to [reduce the use of double underscores in identifiers](https://en.wikipedia.org/wiki/Reserved_word#Reserved_ranges "Reserved name space in C++") any more?

**Comment by RobertElder** [comment]
Interesting, there sure are a lot of rules about reserved identifiers that I wasn't aware of.  I'll get around to fixing them eventually.

**Comment by elfring** [comment]
Would you like to reopen this issue before all affected identifiers from your software will become standard-compliant?

**Comment by RobertElder** [comment]
I just pushed a change to remove the double identifier violations.  FYI I used a variation of these commands:

for i in $(find . -name *.h); do sed -i 's/__/_/g' $i; done
for i in $(find . -name *.c); do sed -i 's/__/_/g' $i; done
... for more file extensions...

**Comment by elfring** [comment]
Thanks for [another source code improvement](https://github.com/RobertElderSoftware/recc/commit/ec25237f6d1bc6233134a61a07716a3c9b962787 "Deletion of some underscores").
